FORMAT: 1A
HOST: https://deckofcardsapi.com

# Deck of Cards API
## Overview

**TRATAMENTO DE ERROS** 

**Atenção!** Todos os serviços seguem o padrão para tratamento de erro do exemplo abaixo:
```
{
    "codigoMensagem": 1,
    "mensagem": "O Serviço está indisponível no momento. Tente novamente mais tarde!",
    "dataServidor": "2022-01-19 13:33:13"
}
```

# Group Novo Deck
## Novo Baralho [/api/deck/new]
### Novo Baralho Nao Embaralhado [GET]
Abra um novo baralho de cartas.
A-espadas, 2-espadas, 3-espadas... seguido de ouros, paus e copas.

Dica: adicione jokers_enabled=true como um parâmetro GET ou POST à ​​sua solicitação para incluir dois Jokers no baralho.

+ Parameters 

    + jokers_enabled (boolean, optional)

+ Response 200 (application/json)

      + Body   
      
                {
                      "sucesso": verdadeiro,
                      "deck_id": "3p40paa87x90",
                      "embaralhado": falso,
                      "restante": 52
                }





### Novo Baralho Nao Embaralhado [POST]
Abra um novo baralho de cartas.
A-espadas, 2-espadas, 3-espadas... seguido de ouros, paus e copas.

Dica: adicione jokers_enabled=true como um parâmetro GET ou POST à ​​sua solicitação para incluir dois Jokers no baralho.

+ Request 
    + Headers

            Accept: application/json
            Content-Type: application/json

    + Attributes

        + jokers_enabled: true (required)
        
    + Body
    
             {
                 "jokers_enabled":"true"
             }

+ Response 200 (application/json)

      + Body   
      
                {
                      "sucesso": verdadeiro,
                      "deck_id": "3p40paa87x90",
                      "embaralhado": falso,
                      "restante": 52
                }
        

### Novo Baralho Embaralhado [POST /api/deck/new/shuffle]
Adicione deck_count para definir o número de decks que você deseja usar. Blackjack normalmente usa 6 baralhos. O padrão é 1.

+ Request (application/json)
    + Headers

            Accept: application/json
            
    + Attributes

        + jokers_enabled: true (required)
        
    + Body
    
             {
                 "deck_count"="1"
             }


+ Response 201 (application/json)

 

    + Body

            {
                    "sucesso": verdadeiro,
                    "deck_id": "3p40paa87x90",
                    "embaralhado": verdadeiro,
                    "restante": 52
            }

# Group Certidões

## Solicitar Certidao via Formulario [/egov/gravarEgov]


### Novo Baralho Nao Embaralhado [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Paeameters (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
            
            
            
## Busca Cartorio [/egov/listarBaseadoExemploEgov]            
            
### Busca Cartorio [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }