FORMAT: 1A
HOST: https://deckofcardsapi.com

# Deck of Cards API
## Overview

**TRATAMENTO DE ERROS** 

**Atenção!** Todos os serviços seguem o padrão para tratamento de erro do exemplo abaixo:
```
{
    "codigoMensagem": 1,
    "mensagem": "O Serviço está indisponível no momento. Tente novamente mais tarde!",
    "dataServidor": "2022-01-19 13:33:13"
}
```

# Group Baralho
## Novo Baralho [/api/deck/new]

### Novo Baralho Nao Embaralhado GET [GET /api/deck/new/{?jokers_enabled}]

Abra um novo baralho de cartas.
A-espadas, 2-espadas, 3-espadas... seguido de ouros, paus e copas.

Dica: adicione jokers_enabled=true como um parâmetro GET ou POST à ​​sua solicitação para incluir dois Jokers no baralho.

+ Parameters

       + jokers_enabled: true (boolean, optional) - ...

+ Response 200 (application/json)

      + Body   
      
                {
                      "sucesso": verdadeiro,
                      "deck_id": "3p40paa87x90",
                      "embaralhado": falso,
                      "restante": 52
                }




### Novo Baralho Nao Embaralhado POST [POST]
Abra um novo baralho de cartas.
A-espadas, 2-espadas, 3-espadas... seguido de ouros, paus e copas.

Dica: adicione jokers_enabled=true como um parâmetro GET ou POST à ​​sua solicitação para incluir dois Jokers no baralho.

+ Request 
    + Headers

            Accept: application/json
            Content-Type: application/json

    + Attributes              
         + jokers_enabled: true (boolean, optional)
             
             
        
    + Body
           

+ Response 200 (application/json)

      + Body   
      
                {
                      "sucesso": verdadeiro,
                      "deck_id": "3p40paa87x90",
                      "embaralhado": falso,
                      "restante": 52
                }
        



### Novo Baralho Embaralhado POST [POST /api/deck/new/shuffle]
Adicione deck_count para definir o número de decks que você deseja usar. Blackjack normalmente usa 6 baralhos. O padrão é 1.

+ Request 
    + Headers
    
            Content-Type: application/json
            Accept: application/json
            
    + Attributes

        + deck_count: 1 (number, required)
        
    + Body
    
             {
                 "deck_count"="1"
             }


+ Response 200 (application/json)

 

    + Body

            {
                    "sucesso": verdadeiro,
                    "deck_id": "3p40paa87x90",
                    "embaralhado": verdadeiro,
                    "restante": 52
            }


## Embaralhar Cartas [/api/deck/{deck_id}/shuffle/{?remaining}]

### Embaralhar Cartas GET [GET]

Não jogue fora um baralho quando tudo o que você quer fazer é embaralhar. Inclua o deck_id em sua chamada para embaralhar suas cartas. Não se preocupe em nos lembrar com quantos baralhos você está jogando.
Adicionar o parâmetro remaining=true  apenas embaralhará as cartas restantes na pilha principal, deixando quaisquer pilhas ou cartas compradas sozinhas.

+ Parameters 

    + deck_id: 3p40paa87x90 (string, required) - Id para identificação do baralho
    + remaining: true (boolean, optional) - Embaralhará as cartas restantes na pilha principal
        

+ Response 200 

    + Body

             {
                "sucesso": verdadeiro,
                "deck_id": "3p40paa87x90",
                "embaralhado": verdadeiro,
                "restante": 52
            }
            
## Tirar Cartas do Baralho [/api/deck/{deck_id}/draw/{?count}]

### Tirar Cartas do Baralho POST [POST]

A variável count define quantas cartas retirar do baralho. Certifique-se de substituir deck_id por um deck_id válido. Usamos o deck_id como um identificador para sabermos quem está jogando com qual deck.
Depois de duas semanas, se nenhuma ação tiver sido feita no baralho, nós o descartamos.

DICA : substitua <<deck_id>> por " new " para criar um baralho embaralhado e comprar cartas desse baralho na mesma solicitação.

+ Parameters 

    + deck_id: 3p40paa87x90 (string, required) - Id para identificação do baralho
    + count: 1 (number, required) - Embaralhará as cartas restantes na pilha principal
        

+ Response 200 

    + Body

            {
                "sucesso": verdadeiro,
                "deck_id": "kxozasf3edqu",
                "cartas": [
                    {
                        "código": "6H",
                        "imagem": "https://deckofcardsapi.com/static/img/6H.png",
                        "imagens": {
                                      "svg": "https://deckofcardsapi.com/static/img/6H.svg",
                                      "png": "https://deckofcardsapi.com/static/img/6H.png"
                                  }, 
                        "valor": "6",
                        "terno": "CORAÇÃO"
                    }, 
                    {
                        "código": "5S",
                        "image": "https://deckofcardsapi.com/static/img/5S.png",
                        "imagens": {
                                      "svg": "https://deckofcardsapi.com/static/img/5S.svg",
                                      "png": "https://deckofcardsapi.com/static/img/5S.png"
                                  }, 
                        "valor": "5",
                        "terno": "ESPADAS"
                    }
                ], 
                "restante": 50
            }